### ISSUE TITLE
Docker file

### ISSUE THREAD

**Issue by matej2** [matej2/instagram-dm-webhook-service#2]
We need docker file similar to [this file](https://github.com/mgp25/Instagram-API/blob/master/Dockerfile), with few changes: base image will be php withouth apache and we need to setup crontabs, which will run `main.php`:

dm-webhook cron file contents:
```
* 0/15 * ? * * * php -f /path-to-dm-bot/main.php
```

**Comment by arc92** [comment]
Can i contribute on this?

**Comment by arc92** [comment]
which service do you want in docker only php??

**Comment by matej2** [comment]
Yes, you are welcome to contribute. We need php image with gd, curl, ffmpeg, ffprobe, mbstring and exif plugins.

**Comment by matej2** [comment]
Before i close the issue.. @arc92 can you test this dockerfile locally? Due to latest issues we are only able to run application on debug mode..
