### ISSUE TITLE
Move conf to env vars 

### ISSUE THREAD

**Issue by matej2** [matej2/instagram-dm-webhook-service#6]
**Describe the solution you'd like**
Instead of json we will have configuration defined in environment variables. Additional libaries may need to be added as dependencies

**Describe alternatives you've considered**
/

**Additional context**
/

**Comment by arc92** [comment]
if i understand what you want , I think it's better to create nested php array and create class with ArrayAccess php interface for retrive the item you want

**Comment by matej2** [comment]
We dont want to store credentials in text format (in json conf file), so we

**Comment by arc92** [comment]
may be my information not good as you but I think you have 3 way
1.use .env file like Laravel
2.use config.php file like what i say above
3.use database to store credentials

**Comment by arc92** [comment]
But i think .env file is good solution since that hidden file in linux system that protect you to  get that file simply.

**Comment by matej2** [comment]
Yes, i agree. You can specify environment variables for example when you run application as Docker container - in this case data is not stored in files, but in memory. However this is only safe in known environments like Docker, because all applications in environment can access this data. We have also been discussing database credential store. 

Currently our application does not require database and this is a big advantage, so we would like to keep it this way. If we later found out that we require databases, we should store passwords with md5 encryption

Overall, credentials in env vars has its pros and cons. In my opinion, this is safe enough for our project. It is good that you pointed out alternatives. I will make more investigations what could be improved here. 

For now, lets do the following: replace json configuration data with environment variables. Remove all conf parameters in main program.

**Comment by arc92** [comment]
If you ok I do changes

**Comment by matej2** [comment]
Yes, you can do this.
